#TREES_DB = "trees_db_angr_arch_cflg_new"
#TREES_DB = "trees_db_angr_flt_m"
#TREES_DB = "trees_db_angr_viz_m"
TREES_DB = "trees_db_angr_cflg_m"

CODE_GRAPH_COLLECTION = "code_graph"
MONGO_CLIENT = "mongodb://localhost:27017/"


code_path = "/Spring_2024/Project_Files/angr_scripts/"
src_path = "/Spring_2024/Project_Files/angr_scripts/src/"
binary_path = "/Spring_2024/Project_Files/angr_scripts/obj/"
trs_src_path = "/Spring_2024/Project_Files/angr_scripts/trs_src/"
trs_binary_path = "/Spring_2024/Project_Files/angr_scripts/trs_obj/"

musl_inc = (
                f"-std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -D_XOPEN_SOURCE=700 "
                f"-I/Spring_2024/musl-1.2.2/arch/x86_64 " # powerpc " #aarch64 " # 
                f"-I/Spring_2024/musl-1.2.2/arch/generic "
                f"-I/Spring_2024/musl-1.2.2/obj/src/internal "
                f"-I/Spring_2024/musl-1.2.2/src/include "
                f"-I/Spring_2024/musl-1.2.2/src/internal "
                f"-I/Spring_2024/musl-1.2.2/obj/include "
                f"-I/Spring_2024/musl-1.2.2/include "
                f"-I/Spring_2024/musl-1.2.2/src/malloc/mallocng "
                f"-I/Spring_2024/musl-1.2.2/src/process "
                f"-I/Spring_2024/musl-1.2.2/src/dirent "
                f"-I/Spring_2024/musl-1.2.2/src/crypt "
                f"-I/Spring_2024/musl-1.2.2/src/math "
                f"-I/Spring_2024/musl-1.2.2/src/ctype "
                f"-I/Spring_2024/musl-1.2.2/src/errno "
                f"-I/Spring_2024/musl-1.2.2/src/ipc "
                f"-I/Spring_2024/musl-1.2.2/src/locale "
                f"-I/Spring_2024/musl-1.2.2/src/multibyte "
                f"-I/Spring_2024/musl-1.2.2/src/network "
                f"-I/Spring_2024/musl-1.2.2/src/passwd "
                f"-I/Spring_2024/musl-1.2.2/src/prng "
                f"-I/Spring_2024/musl-1.2.2/src/regex "
                f"-I/Spring_2024/musl-1.2.2/src/search "
                f"-I/Spring_2024/musl-1.2.2/src/stdio "
                f"-D__uint128_t=int "
           )

openssl_inc = (
			f"-I/Spring_2024/openssl-master/include "
			f"-I/Spring_2024/openssl-master/ssl "
			f"-I/Spring_2024/openssl-master/crypto "
			f"-I/Spring_2024/openssl-master/crypto/aes "
			f"-I/Spring_2024/openssl-master/crypto/ocsp "
			f"-I/Spring_2024/openssl-master/crypto/rsa "
			f"-I/Spring_2024/openssl-master/crypto/asn1 "
			f"-I/Spring_2024/openssl-master/crypto/async "
			f"-I/Spring_2024/openssl-master/crypto/bio "
			f"-I/Spring_2024/openssl-master/crypto/rc5 "
			f"-I/Spring_2024/openssl-master/crypto/des "
			f"-I/Spring_2024/openssl-master/crypto/hmac "
			f"-I/Spring_2024/openssl-master/crypto/sha "
			f"-I/Spring_2024/openssl-master/crypto/property "
			f"-I/Spring_2024/openssl-master/crypto/encode_decode "
			f"-I/Spring_2024/openssl-master/crypto/objects "
			f"-I/Spring_2024/openssl-master/crypto/bn "
			f"-I/Spring_2024/openssl-master/crypto/dh "
			f"-I/Spring_2024/openssl-master/providers/implementations/ciphers "
			f"-I/Spring_2024/openssl-master/providers/implementations/include "
			f"-I/Spring_2024/openssl-master/providers/common/include "
			f"-I/Spring_2024/openssl-master/crypto/x509 "
			f"-I/Spring_2024/openssl-master/crypto/pkcs7 "
			f"-I/Spring_2024/openssl-master/crypto/bf "
			f"-I/Spring_2024/openssl-master/crypto/camellia "
			f"-I/Spring_2024/openssl-master/crypto/cast "
			f"-I/Spring_2024/openssl-master/crypto/cmp "
			f"-I/Spring_2024/openssl-master/crypto/cms "
			f"-I/Spring_2024/openssl-master/crypto/comp "
			f"-I/Spring_2024/openssl-master/crypto/conf "
			f"-I/Spring_2024/openssl-master/crypto/crmf "
			f"-I/Spring_2024/openssl-master/crypto/ct "
			f"-I/Spring_2024/openssl-master/crypto/dsa "
			f"-I/Spring_2024/openssl-master/crypto/dso "
			f"-I/Spring_2024/openssl-master/crypto/ec "
			f"-I/Spring_2024/openssl-master/crypto/evp "
			f"-I/Spring_2024/openssl-master/crypto/engine "
			f"-I/Spring_2024/openssl-master/crypto/err "
			f"-I/Spring_2024/openssl-master/crypto/idea "
			f"-I/Spring_2024/openssl-master/crypto/lhash "
			f"-I/Spring_2024/openssl-master/crypto/md4 "
			f"-I/Spring_2024/openssl-master/crypto/md5 "
			f"-I/Spring_2024/openssl-master/crypto/objects "
			f"-I/Spring_2024/openssl-master/crypto/pem "
			f"-I/Spring_2024/openssl-master/crypto/pkcs7 "
			f"-I/Spring_2024/openssl-master/crypto/pkcs12 "
			f"-I/Spring_2024/openssl-master/crypto/property "
			f"-I/Spring_2024/openssl-master/crypto/rand "
			f"-I/Spring_2024/openssl-master/crypto/rc2 "
			f"-I/Spring_2024/openssl-master/crypto/rc4 "
			f"-I/Spring_2024/openssl-master/crypto/ripemd "
			f"-I/Spring_2024/openssl-master/crypto/seed "
			f"-I/Spring_2024/openssl-master/crypto/sm3 "
			f"-I/Spring_2024/openssl-master/crypto/store "
			f"-I/Spring_2024/openssl-master/crypto/ts "
			f"-I/Spring_2024/openssl-master/crypto/ui "
			f"-I/Spring_2024/openssl-master/crypto/whrlpool "
			f"-I/Spring_2024/openssl-master/crypto/x509 "
			f"-I/Spring_2024/openssl-master/ssl/quic "
			f"-I/Spring_2024/openssl-master/ssl/record "
			f"-I/Spring_2024/openssl-master/ssl/statem "
			f"-D_Atomic=\"\" "
              )

curl_inc = (
                f"-I/Spring_2024/curl-curl-7_85_0/include "
                f"-I/Spring_2024/curl-curl-7_85_0/lib "
                f"-I/Spring_2024/curl-curl-7_85_0/lib/vtls "
                f"-I/Spring_2024/curl-curl-7_85_0/lib/vauth "
                f"-I/Spring_2024/curl-curl-7_85_0/lib/vquic "
                f"-I/Spring_2024/curl-curl-7_85_0/lib/vssh "
                f"-I/Spring_2024/curl-curl-7_85_0/src/ "
                f"-DHAVE_CONFIG_H -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -DUSE_ALARM_TIMEOUT "
                f"-fvisibility=hidden -Werror-implicit-function-declaration -Wno-system-headers -pthread "
           )

sqlite_inc = (
                f"-I/Spring_2024/curl-curl-7_85_0/src/ "
                f"-I/Summer_2024/datasets/sqlite/bld "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/src "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/rtree "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/icu "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/fts3 "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/async "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/session "
                f"-I/Summer_2024/datasets/sqlite/sqlite-master/ext/userauth "
                f"-DSQLITE_OS_UNIX=1 "
                f"-D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS "
                f"-DSQLITE_HAVE_ZLIB=1 -DHAVE_READLINE=0 -DHAVE_EDITLINE=0 -DHAVE_LINENOISE=0 -DSQLITE_DQS=0 -DSQLITE_ENABLE_FTS4 "
                f"-DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STMTVTAB "
                f"-DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC "
                f"-DSQLITE_STRICT_SUBTYPE=1 -D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
           )

redis_inc = (
               f"-I/Summer_2024/datasets/redis-unstable/src "
               f"-I/Summer_2024/datasets/redis-unstable/deps/hiredis "
               f"-I/Summer_2024/datasets/redis-unstable/deps/jemalloc/include "
               f"-I/Summer_2024/datasets/redis-unstable/deps/lua/src "
               f"-I/Summer_2024/datasets/redis-unstable/deps/fpconv "
               f"-I/Summer_2024/datasets/redis-unstable/deps/hdr_histogram "
               f"-I/Summer_2024/datasets/redis-unstable/deps/linenoise "
               f"-std=gnu11 -fPIC -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers "
               f"-Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-attributes "
               f"-DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE "
               f"-D_Atomic=\"\" -D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
            )

coreutils_inc = (
                   f"-I/Summer_2024/datasets/coreutils "
                   f"-I/Summer_2024/datasets/coreutils/src "
                   f"-I/Summer_2024/datasets/coreutils/lib "
                   f"-I/Summer_2024/datasets/coreutils/gnulib/lib "
                   f"-I/Summer_2024/datasets/coreutils/gl/lib "
                   f"-Warith-conversion -Wbad-function-cast -Wcast-align=strict -Wdate-time -Wdisabled-optimization -Wduplicated-cond -Wextra -Wformat-signedness -Winit-self "
                   f"-Winvalid-pch -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnull-dereference -Wopenmp-simd -Woverlength-strings -Wpacked -Wpointer-arith "
                   f"-Wshadow -Wstrict-prototypes -Wsuggest-attribute=cold -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=malloc -Wsuggest-attribute=noreturn "
                   f"-Wsuggest-attribute=pure -Wsuggest-final-methods -Wsuggest-final-types -Wsync-nand -Wtrampolines -Wunknown-pragmas -Wvariadic-macros -Wvla -Wwrite-strings -Warray-bounds=2 "
                   f"-Wattribute-alias=2 -Wformat=2 -Wimplicit-fallthrough=5 -Wshift-overflow=2 -Wunused-const-variable=2 -Wvla-larger-than=4031 -Wno-sign-compare -Wno-unused-parameter "
                   f"-Wno-format-nonliteral -fdiagnostics-show-option -funit-at-a-time -Wno-return-local-addr -Wno-stringop-overflow -Wno-cast-qual -Wno-conversion -Wno-float-equal "
                   f"-Wno-sign-compare -Wno-undef -Wno-unused-function -Wno-unused-parameter -Wno-float-conversion -Wimplicit-fallthrough -Wno-pedantic -Wno-sign-conversion -Wno-type-limits "
                   f"-Wno-unsuffixed-float-constants -DBASE_TYPE=64 -D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float -D_Noreturn=\"\" "
                )

imagemagick_inc = (
                     f"-I/Summer_2024/datasets/ImageMagick-main "
                     f"-I/Summer_2024/datasets/ImageMagick-main/config "    
                     f"-DHAVE_CONFIG_H " 
                     f"-DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32  -Wall -mtune=core2 -fexceptions -pthread "
                     f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
                  )


libtomcrypt_inc = (
                     f"-I/Summer_2024/datasets/libtomcrypt-develop/src/headers/ "
                     f"-DLTC_SOURCE -Wall -Wsign-compare -Wshadow -Wextra -Wsystem-headers -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wpointer-arith -Wdeclaration-after-statement "
                     f"-Wwrite-strings -DGIT_VERSION=\"1.18.2-develop\" "
                  )

binutils_inc = (
                  f"-DHAVE_x86_64_elf64_vec -DHAVE_i386_elf32_vec -DHAVE_iamcu_elf32_vec -DHAVE_x86_64_elf32_vec -DHAVE_i386_pei_vec -DHAVE_x86_64_pe_vec -DHAVE_x86_64_pei_vec "
                  f"-DHAVE_elf64_le_vec -DHAVE_elf64_be_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec "
                  f"-DHAVE_CONFIG_H "
                  f"-I/Summer_2024/datasets/binutils-gdb/binutils "
                  f"-I/Summer_2024/datasets/binutils-gdb/bfd "
                  f"-I/Summer_2024/datasets/binutils-gdb/include "
                  f"-DLOCALEDIR='\"/usr/local/share/locale\"' -DBINDIR='\"/usr/local/bin\"' -DLIBDIR='\"/usr/local/lib\"' " 
                  f"-Dbin_dummy_emulation=bin_vanilla_emulation -W -Wall -Wstrict-prototypes -Wmissing-prototypes "
                  f"-Wshadow -Wstack-usage=262144 "
                  f"-I/Summer_2024/datasets/binutils-gdb/zlib "
                  f"-I/Summer_2024/datasets/binutils-gdb/gas/config "
                  f"-I/Summer_2024/datasets/binutils-gdb/gas/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/gprof/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/ld/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/libbacktrace/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/libctf/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/libdecnumber/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/libiberty/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/libsframe/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/opcodes/ "
                  f"-I/Summer_2024/datasets/binutils-gdb/readline/readline/ "
                  f"-DELF_LIST_OPTIONS=true -DELF_SHLIB_LIST_OPTIONS=true -DELF_PLT_UNWIND_LIST_OPTIONS=true -D_GNU_SOURCE -DNOBFD=0 " #-std=gnu99 "
                  f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
               )

libmongoc_inc = (
                   f"-DHAVE_STDARG_H -DHAVE_UNISTD_H -DKMS_MESSAGE_ENABLE_CRYPTO -DKMS_MESSAGE_ENABLE_CRYPTO_LIBCRYPTO -DKMS_MESSAGE_LITTLE_ENDIAN -DKMS_MSG_STATIC "
                   f"-DMCOMMON_NAME_PREFIX=_mongoc_mcommon -DMONGOC_COMPILATION -DUTF8PROC_STATIC -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -Dmongoc_shared_EXPORTS "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/zlib-1.2.13 "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/utf8proc-2.8.0 "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/uthash "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libmongoc/../kms-message/src "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libmongoc/src "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libmongoc/src/mongoc "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libmongoc/../../src/common "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libmongoc/../../src "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libbson/src "
                   f"-I/Summer_2024/datasets/mongo-c-driver-master/src/common "
                   f"-DNDEBUG -fPIC -std=c99 "
                   # libbson compilation
                   #f"-DNDEBUG -fPIC -std=c99 "
                   #f"-DBSON_COMPILATION -DJSONSL_PARSE_NAN -DMCOMMON_NAME_PREFIX=_bson_mcommon -Dbson_shared_EXPORTS "
                   #f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libbson/src "
                   #f"-I/Summer_2024/datasets/mongo-c-driver-master/src/libbson/src/bson "
                   #f"-I/Summer_2024/datasets/mongo-c-driver-master/src/common/ "
                   #f"-I/Summer_2024/datasets/mongo-c-driver-master/src/utf8proc-2.8.0/ "
                   #f"-fvisibility=hidden "
                )

alsa_inc = (
             f"-DHAVE_CONFIG_H "
             f"-I/Summer_2024/datasets/alsa-lib-master/include "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/alisp "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/control "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/hwdep "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/mixer "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/pcm "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/rawmidi "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/seq "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/timer "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/topology "
             f"-I/Summer_2024/datasets/alsa-lib-master/src/ucm "
             f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
          )

gsl_inc = (
             f"-DHAVE_CONFIG_H "
             f"-I/Summer_2024/datasets/gsl-master/ "
             f"-I/Summer_2024/datasets/gsl-master/blas "
             f"-I/Summer_2024/datasets/gsl-master/block "
             f"-I/Summer_2024/datasets/gsl-master/bspline "
             f"-I/Summer_2024/datasets/gsl-master/bst "
             f"-I/Summer_2024/datasets/gsl-master/cblas "
             f"-I/Summer_2024/datasets/gsl-master/cdf "
             f"-I/Summer_2024/datasets/gsl-master/cheb "
             f"-I/Summer_2024/datasets/gsl-master/combination "
             f"-I/Summer_2024/datasets/gsl-master/complex "
             f"-I/Summer_2024/datasets/gsl-master/const "
             f"-I/Summer_2024/datasets/gsl-master/deriv "
             f"-I/Summer_2024/datasets/gsl-master/dht "
             f"-I/Summer_2024/datasets/gsl-master/diff "
             f"-I/Summer_2024/datasets/gsl-master/eigen "
             f"-I/Summer_2024/datasets/gsl-master/err "
             f"-I/Summer_2024/datasets/gsl-master/fft "
             f"-I/Summer_2024/datasets/gsl-master/filter "
             f"-I/Summer_2024/datasets/gsl-master/fit "
             f"-I/Summer_2024/datasets/gsl-master/histogram "
             f"-I/Summer_2024/datasets/gsl-master/ieee-utils "
             f"-I/Summer_2024/datasets/gsl-master/integration "
             f"-I/Summer_2024/datasets/gsl-master/interpolation "
             f"-I/Summer_2024/datasets/gsl-master/matrix "
             f"-I/Summer_2024/datasets/gsl-master/min "
             f"-I/Summer_2024/datasets/gsl-master/monte "
             f"-I/Summer_2024/datasets/gsl-master/movstat "
             f"-I/Summer_2024/datasets/gsl-master/multifit "
             f"-I/Summer_2024/datasets/gsl-master/multifit_nlinear "
             f"-I/Summer_2024/datasets/gsl-master/multilarge "
             f"-I/Summer_2024/datasets/gsl-master/multilarge_nlinear "
             f"-I/Summer_2024/datasets/gsl-master/multimin "
             f"-I/Summer_2024/datasets/gsl-master/multiroots "
             f"-I/Summer_2024/datasets/gsl-master/multiset "
             f"-I/Summer_2024/datasets/gsl-master/ntuple "
             f"-I/Summer_2024/datasets/gsl-master/ode-initval "
             f"-I/Summer_2024/datasets/gsl-master/ode-initval2 "
             f"-I/Summer_2024/datasets/gsl-master/permutation "
             f"-I/Summer_2024/datasets/gsl-master/poly "
             f"-I/Summer_2024/datasets/gsl-master/qrng "
             f"-I/Summer_2024/datasets/gsl-master/randist "
             f"-I/Summer_2024/datasets/gsl-master/rng "
             f"-I/Summer_2024/datasets/gsl-master/roots "
             f"-I/Summer_2024/datasets/gsl-master/rstat "
             f"-I/Summer_2024/datasets/gsl-master/siman "
             f"-I/Summer_2024/datasets/gsl-master/sort "
             f"-I/Summer_2024/datasets/gsl-master/spblas "
             f"-I/Summer_2024/datasets/gsl-master/specfunc "
             f"-I/Summer_2024/datasets/gsl-master/splinalg "
             f"-I/Summer_2024/datasets/gsl-master/spmatrix "
             f"-I/Summer_2024/datasets/gsl-master/statistics "
             f"-I/Summer_2024/datasets/gsl-master/sum "
             f"-I/Summer_2024/datasets/gsl-master/sys "
             f"-I/Summer_2024/datasets/gsl-master/test "
             f"-I/Summer_2024/datasets/gsl-master/vector "
             f"-I/Summer_2024/datasets/gsl-master/wavelet "
             f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
          )


libmicrohttpd_inc = (
                       f"-DHAVE_CONFIG_H "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/microhttpd "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/include  "
                       f"-I/Summer_2024/datasets/libmicrohttpd "
                       #f"-I/Summer_2024/datasets/libmicrohttpd/src/lib "
                       #f"-I/Summer_2024/datasets/libmicrohttpd/src/microhttpd_ws "
                       #f"-I/Summer_2024/datasets/libmicrohttpd/src/gnutls "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/testcurl "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/testzzuf "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/examples "
                       f"-I/Summer_2024/datasets/libmicrohttpd/src/tools "
                       f"-D_GNU_SOURCE -D_XOPEN_SOURCE=700 -fno-strict-aliasing "
                       f"-DBUILDING_MHD_LIB=1 -fvisibility=hidden -pthread -D_Noreturn=\" \" "
                       #f"-D_MHD_PUT_64BIT_LE_UNALIGNED -D_MHD_PUT_64BIT_BE_UNALIGNED -D_MHD_GET_32BIT_LE_UNALIGNED -D_MHD_PUT_32BIT_LE_UNALIGNED "
                       f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float "
                    )

libxml2_inc = (
                 f"-DHAVE_CONFIG_H "
                 f"-I/Summer_2024/datasets/libxml2-master "
                 f"-I/Summer_2024/datasets/libxml2-master/include "
                 f"-I/Summer_2024/datasets/libxml2-master/fuzz "
                 f"-I/Summer_2024/datasets/libxml2-master/os400 "
                 f"-DSYSCONFDIR='\"/usr/local/etc\"'  -pedantic -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wstrict-prototypes "
                 f"-Wmissing-prototypes -Wno-long-long -Wno-format-extra-args "
              )

allegro_inc = (
                 f"-Dallegro_EXPORTS "
                 f"-I/Summer_2024/datasets/allegro5-master/include "
                 f"-I/Summer_2024/datasets/allegro5-master/build/include "
                 f"-I/Summer_2024/datasets/allegro5-master/src/opengl "
                 #f"-I/Summer_2024/datasets/allegro5-master/examples "
                 #f"-I/Summer_2024/datasets/allegro5-master/demos/skater/src "
                 #f"-I/Summer_2024/datasets/allegro5-master/addons/acodec "
                 f"-msse -W -Wall -Wpointer-arith -Wmissing-declarations -Wstrict-prototypes -Wmissing-prototypes -DNDEBUG -fPIC  -DALLEGRO_SRC  -DALLEGRO_LIB_BUILD "
              )

dbus_inc = (
              f"-DDBUS_COMPILATION -DHAVE_CONFIG_H -Ddbus_1_EXPORTS -DDBUS_ENABLE_CONTAINERS "
              f"-I/Summer_2024/datasets/dbus-master/. "
              f"-I/Summer_2024/datasets/dbus-master "
              f"-I/Summer_2024/datasets/dbus-master/dbus "
              f"-I/Summer_2024/datasets/dbus-master/bus "
              f"-I/Summer_2024/datasets/dbus-master/tools "
              f"-fno-common "
              #f"-Wall -Warray-bounds -Wcast-align -Wchar-subscripts -Wdeclaration-after-statement -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra "
              #f"-Wfloat-equal -Wformat-nonliteral -Wformat-security -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wjump-misses-init -Wlogical-op -Wmissing-declarations "
              #f"-Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wno-error=missing-field-initializers -Wno-error=unused-label "
              #f"-Wno-error=unused-parameter -Wno-missing-field-initializers -Wno-unused-label -Wno-unused-parameter -Wnull-dereference -Wold-style-definition -Wpacked -Wpointer-arith "
              #f"-Wpointer-sign -Wredundant-decls -Wrestrict -Wreturn-type -Wshadow -Wsign-compare -Wstrict-aliasing -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef "
              #f"-Wunused-but-set-variable -Wwrite-strings -Wno-error=inline -Wno-error=overloaded-virtual -Wno-error=missing-field-initializers -Wno-error=null-dereference "
              #f"-Wno-error=strict-aliasing -Wno-error=unused-parameter -Wno-unused-parameter "
              f"-D_Float32=float -D_Float64=float -D_Float128=float -D_Float32x=float -D_Float64x=float -D_Float128x=float -D_Atomic=\"\" "
           )

igraph_inc = (
                f"-DIGRAPH_STATIC -DNCOMPLEX -D_POSIX_C_SOURCE=200809L "
                f"-I/Summer_2024/datasets/igraph/include "
                f"-I/Summer_2024/datasets/igraph/build/include "
                f"-I/Summer_2024/datasets/igraph/src/centrality "
                f"-I/Summer_2024/datasets/igraph/src "
                f"-I/Summer_2024/datasets/igraph/src/core "
                f"-I/Summer_2024/datasets/igraph/build/src "
                f"-I/Summer_2024/datasets/igraph/src/cliques "
                f"-I/Summer_2024/datasets/igraph/src/cliques/cliquer "
                f"-I/Summer_2024/datasets/igraph/src/constructors "
                f"-I/Summer_2024/datasets/igraph/src/flow "
                f"-I/Summer_2024/datasets/igraph/src/graph "
                f"-I/Summer_2024/datasets/igraph/src/internal "
                f"-I/Summer_2024/datasets/igraph/src/io "
                f"-I/Summer_2024/datasets/igraph/src/isomorphism "
                f"-I/Summer_2024/datasets/igraph/src/layout "
                f"-I/Summer_2024/datasets/igraph/src/linalg "
                f"-I/Summer_2024/datasets/igraph/src/math "
                f"-I/Summer_2024/datasets/igraph/src/misc "
                f"-I/Summer_2024/datasets/igraph/src/operators "
                f"-I/Summer_2024/datasets/igraph/src/properties "
                f"-I/Summer_2024/datasets/igraph/src/random "
                f"-DNDEBUG -fvisibility=hidden -std=gnu99 "
                f"-DINFINITY=1/0 -DNAN=0.0/-7.08396418532 "
             )

#transformation_cmd = "--Transform=Flatten" #"--Transform=Virtualize"  # #
transformation_cmd = "--Transform=Virtualize"  # #
transformation_cmd_2 = "--Transform=EncodeArithmetic"  #"--Transform=Flatten" #

# Platform information

architecture     = "x86_64" #"aarch64" #"mips64" # #
library          = "igraph" #"dbus" #"allegro" #"libxml2" #"libmicrohttpd" #"gsl" #"alsa" #"libmongoc" #"binutils" #"libtomcrypt" #"imagemagick" #"coreutils" #"redis" #"sqlite" #"curl" #"musl" #"openssl" ##  # zlib - compiled as part of binutils
compiler         = "gcc"
compiler_version = "11.4.0"
cpu              = "13th Gen Intel(R) Core(TM) i9-13900HX"
os_type          = "Linux ubuntu"
os_version       = "22.04.3 LTS"
transformation   = "N/A" #"Virtualize" #"Flatten" #"EncodeArithmetic, Virtualize" #"EncodeArithmetic, Flatten" #
compiler_flags   = "-c"


